name: toroid-update-index
on:
  schedule:
    # At 00:00 on Sunday
    - cron: '0 0 * * 0'

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_CHECKOUT_TOKEN }}
      - name: Update index
        run: ./refresh_tor_index.sh
      - name: Add and commit
        uses: EndBug/add-and-commit@v7
        with:
          add: 'site/tor.json'
          author_name: Evan Savage
          author_email: savage.evan@gmail.com
